# Generated by Django 4.2.4 on 2023-09-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
